name: macOS Build

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:

    runs-on: macOS-latest


    steps:
    - uses: actions/checkout@v1
    - name: sudo apt install...
      run: brew install cmake ninja
    - name: cd subprojects/luajit && make
      run: cd subprojects/luajit && make
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.6
    - name: mkdir build
      run: mkdir build
    - name: cd build && cmake .. -GNinja
      run: cd build && cmake .. -GNinja
    - name: cd build && ninja
      run: cd build && ninja
    - name: cp build/nibble src
      run: cp build/nibble src
    - name: mkdir nibble
      run: mkdir nibble
    - name: cp build/nibble nibble
      run: cp build/nibble nibble
    - name: cp src/{apps,frameworks} nibble
      run: cp -r src/{apps,frameworks} nibble
    - uses: actions/upload-artifact@master
      with:
        name: Nibble for macOS (x64)
        path: nibble/
