name: Linux Build

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: sudo apt install...
      run: sudo apt install ninja-build libasound2-dev
    - name: cd subprojects/luajit && make
      run: cd subprojects/luajit && make
    - name: mkdir build
      run: mkdir build
    - name: cd build && cmake .. -GNinja
      run: cd build && cmake .. -GNinja
    - name: cd build && ninja
      run: cd build && ninja
    - name: cp build/nibble src
      run: cp build/nibble src
    - name: mv src nibble
      run: mv src nibble
    - name: zip -r nibble-linux64.zip nibble
      run: zip -r nibble-linux64.zip nibble
    - uses: actions/upload-artifact@master
      with:
        name: Nibble for Linux (x64)
        path: nibble-linux64.zip
